export { default as VuIconSvgDynamic } from './src/icon-svg-dynamic.vue'
export { default as VuIconSvgSlot } from './src/icon-svg-slot.vue'
export { default as AntDesignMenuFoldOutlined } from './src/svgs/ant-design-menu-fold-outlined.vue'
export { default as AntDesignMenuUnfoldOutlined } from './src/svgs/ant-design-menu-unfold-outlined.vue'
export { default as EpCloseIcon } from './src/svgs/ep-close.vue'
